[phases.setup]
nixPkgs = ["php82", "composer"]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "cp .env.example .env",
  "php artisan key:generate"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=3000"